### ISSUE TITLE
crashing when tweet has line break

### ISSUE THREAD

**Issue by Skeyelab** [Mhyles/DonaldTrumpStockMonitor#8]
Seems to be crashing when the tweet file has a line break.

```➜  DonaldTrumpStockMonitor git:(master) ✗ python Trump.py
Trump.py:189: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if word.lower() == line.strip():
Traceback (most recent call last):
  File "Trump.py", line 387, in <module>
    main()
  File "Trump.py", line 384, in main
    main()
  File "Trump.py", line 361, in main
    matches = Companies(new_tweet).check_companies()
  File "Trump.py", line 183, in check_companies
    if item in self.tweet:
TypeError: argument of type 'NoneType' is not iterable```

**Comment by semaaJ** [comment]
Your running this off a server are you? I had this error when I tried to run it off a server originally too, which is strange because it works perfectly on my PC. I've fixed the issue and I'll get back to you ASAP with the fixed code when i can get access to my PC.

**Comment by semaaJ** [comment]
Give it a try with the updated files.

**Comment by Skeyelab** [comment]
I always run in a Unix environment. :)

Yes, this fixed it.
